### ISSUE TITLE
include path doesn't seem to be added

### ISSUE THREAD

**Issue by waspinator** [iH8c0ff33/mongoose-os-ide-vscode#1]
- macOS High Sierra
- mos 20180208-182630/master@ab7f50e1+
- gcc symlinked to clang 9 (Apple LLVM version 9.0.0 (clang-900.0.39.2)
  - also have gcc-7 installed (7.3.0)
- Code 1.20.1 
- Mongoose OS IDE 0.3.0. 
- C/C++ 0.15.0

`#include "mgos.h"` is squiggled green and cannot be found.

not sure what the instruction to run `mos-ide: Generate Mongoose-OS cpp config` means. I don't have the cpp-configuration.json file in my .vscode directory.

**Comment by iH8c0ff33** [comment]
I'm sorry but this repo isn't related to the mongoose-os viscose extension you can find on the [marketplace](https://marketplace.visualstudio.com/items?itemName=mongoose-os.mongoose-os-ide). It's an old repo for an extension I developed to get automatic mongoose-os completion. AFAIK the new (and official) mongoose-os extension doesn't support automatic cpp-configuration generation 😢 

PS: You could try to install my extension from this repo, I haven't tested it recently but it should work...

**Comment by waspinator** [comment]
Oh, I'm sorry. I think I was confused because of the similar names. It's too bad the official version doesn't seem to be on github.
